[package]
name = "nova-client"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "NovaDB SDK: client library for applications to talk to a NovaDB server"

[dependencies]
nova-core = { path = "../nova-core", version = "0.1.0" }
nova-server = { path = "../nova-server", version = "0.1.0" }

[dev-dependencies]
nova-executor = { path = "../nova-executor", version = "0.1.0" }

[lints]
workspace = true
