[package]
name = "nova-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "NovaDB interactive command-line interface"

[[bin]]
name = "nova"
path = "src/main.rs"

[dependencies]
nova-client = { path = "../../crates/nova-client", version = "0.1.0" }
nova-core = { path = "../../crates/nova-core", version = "0.1.0" }

[lints]
workspace = true
